export const URL_API = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export const URL_AUTH_API =  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export const URL_LOGIN_API =  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
export const URL_MAP_API =  "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
